services:
  github-exporter:
    tty: true
    stdin_open: true
    expose:
      - 9171
    ports:
      - 9171:9171
    image: ghcr.io/yongenaelf/github-exporter:sha-a19c694
    env_file:
      - .env