name: Container Scan
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  container-scan:
    name: Container Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$calculatedSha" >> "$GITHUB_OUTPUT"

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: 'ghcr.io/${{ github.repository }}/github-exporter:${{ steps.vars.outputs.short_sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
